source 'https://rubygems.org'

gem 'activesupport',    '~> 4.2.5'
gem 'aws-sdk',          '~> 2.2'
gem 'berkshelf',        '~> 5.6.5'
gem 'cfndsl',           '~> 0.15.3'
gem 'diffy',            '~> 3.0.7'
gem 'kitchen-ec2',      '~> 0.10.0'
gem 'kitchen-sync',     '~> 1.1.1'
gem 'kitchen-vagrant',  '~> 1.3'
gem 'net-ssh',          '~> 2.9.2'
gem 'parallel',         '~> 1.6.1'
